#!/bin/bash

echo "¿Qué deseas hacer?"
echo "1. Hacer respaldo de los dispositivos USB conectados"
echo "2. Importar respaldo de dispositivos USB"
read -p "Ingresa el número de la opción deseada: " opcion

if [ $opcion -eq 1 ]
then
# Hacer respaldo de los dispositivos USB conectados
mkdir -p /tmp/usbsave
for device in $(ls /sys/bus/usb/devices/)
do
if [ -d "/sys/bus/usb/devices/$device" ] && [ "$device" != "." ] && [ "$device" != ".." ]
then
sudo usb-modeswitch -W -D -v 0x12d1 -p 0x1446 -s 0x12d1 -c /etc/usb_modeswitch.d/$device
sudo cp -R /sys/bus/usb/devices/$device /tmp/usbsave
fi
done
echo "Respaldo de dispositivos USB realizado con éxito en /tmp/usbsave"
elif [ $opcion -eq 2 ]
then
# Importar respaldo de dispositivos USB
for device in $(ls /tmp/usbsave)
do
if [ -d "/tmp/usbsave/$device" ] && [ "$device" != "." ] && [ "$device" != ".." ]
then
sudo cp -R /tmp/usbsave/$device /sys/bus/usb/devices/
fi
done
echo "Importación de respaldo de dispositivos USB realizada con éxito"
else
echo "Opción inválida"
fi
